// Glyph geometry, generated by tools/glyph.py. A character carries three things
// a vessel can be built from: the outlines of its pieces, a relief height field
// of its strokes, and the profile it sweeps when revolved about its own axis.
import cha from './cha.js'
import hu from './hu.js'

export const GLYPHS = { cha, hu }
